### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by PLNech**
# Changes:
- New module name
- Performance improvements
- Option to raise exceptions, defaults to `if DEBUG is true`
- Option to auto-index at registration time
- Update multiple records with a QuerySet

# Fixes:
- Fields (syntax, compatibility with Django 1.10)
- Algolia_reindex command with `batchsize` argument on python34-django18

-----

Hey @dethi, I hope this message finds you well! was there a specific reason for not merging your changes in `master`? Your review is welcome (if you want to) 🙂

### CODE REVIEW

**Comment by dethi** [comment]
Hi @PLNech,

The main reasons were:
- lake of time
- docs
- breaking change 1 month after the first release. The idea was to wait and collect feedback and issues, so I can fix them in the new release (and avoid another breaking change two months later...)

**Comment by PLNech** [comment]
Hi @dethi, thanks for the explanation :)
- `time`: I'm dedicating some to give this integration some love 😉
- `docs`: WDYM? I see you did some updates to the readme
- `breaking change/feedback`: I think now we can release a new one, and we got a few feedback/issues I'll try to address by the way :)

**Comment by PLNech** [comment]
@dethi: Do you remember what where the `Performance Improvements` you described in this PR? (I can't find mentions of them in those commits, or maybe you meant f3eb11e that improved test runtime performance?)

**Comment by dethi** [comment]
No, sorry. It was too long ago.

**Pull request merged**
