### PR TITLE
Fix reindex_all() and save_record() when should_index is not callable

### PR DESCRIPTION
**Pull request by m-vdb**
Hello there,

When `should_index` is not callable, both `reindex_all()` and `save_record()` are broken. Here is an attempt to fix it. I've used test-driven development to avoid any regression,

Cheers 👍

### CODE REVIEW

**Comment by PLNech** [comment]
Hi @m-vdb, thanks for your contribution and my apologies for the slow reply!

This looks good to me 👍

**Comment by m-vdb** [comment]
thanks! Any chance of a pypi release?

**Comment by PLNech** [comment]
But of course! Released as [1.5.1](https://github.com/algolia/algoliasearch-django/releases/tag/1.5.1).

**Comment by m-vdb** [comment]
Noice!

**Pull request merged**
