### PR TITLE
chore: release v4

### PR DESCRIPTION
**Pull request by shortcuts**
## 🧭 What and Why

🎟 Related Issue: https://algolia.atlassian.net/browse/DI-3248

### Changes included:

```
2024-12-26 4.0.0
  * [MAJOR] drop support for python <3.8 [#336](https://github.com/algolia/algoliasearch-django/pull/336)
  * [MAJOR] drop support for django <4.0 [#336](https://github.com/algolia/algoliasearch-django/pull/336)
  * [MAJOR] remove method `clear_index` in favor of `clear_objects` [#336](https://github.com/algolia/algoliasearch-django/pull/336)
```

### CODE REVIEW

**Review by morganleroi — APPROVED** [review]
🆒

**Comment by arkid15r** [comment]
@morganleroi @shortcuts could you check why [v4 hasn't been published](https://github.com/algolia/algoliasearch-django/actions/runs/12502784634/job/34882534218#step:5:201)?

**Comment by shortcuts** [comment]
> @morganleroi @shortcuts could you check why [v4 hasn't been published](https://github.com/algolia/algoliasearch-django/actions/runs/12502784634/job/34882534218#step:5:201)?

hey, it has just been published!

**Comment by arkid15r** [comment]
@shortcuts thank you!

**Pull request merged**
