### PR TITLE
Check that geo_field callable returns something valid

### PR DESCRIPTION
**Pull request by adamghill**
I have some models that have a valid geo location, but others that don't. This will prevent those models without a valid location from preventing indexing.

### CODE REVIEW

**Comment by redox** [comment]
Hey @adamghill, thanks for contributing. Looks good, do you mind removing the `Update version.` (8ecdc5e) commit from the PR?

**Comment by adamghill** [comment]
Sure @redox! Thanks for looking at the PR. I reverted the version change.

**Comment by adamghill** [comment]
@redox I was trying to update the tests to make sure my change didn't break anything. I installed pandoc with `brew install pandoc`, created a virtualenv, sourced it, `pip install -r requirements.txt` and then `python runtests.py`, but am getting this error:
```
Traceback (most recent call last):
  File "runtests.py", line 20, in <module>
    main()
  File "runtests.py", line 13, in main
    django.setup()
  File "/Users/ahill/Source/algoliasearch-django/.venv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ahill/Source/algoliasearch-django/.venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/ahill/Source/algoliasearch-django/.venv/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named algoliasearch
```

Am I missing something simple?

**Comment by dethi** [comment]
@adamghill launch the tests with tox: `tox`

**Comment by dethi** [comment]
You are getting this error because run_test.py setup django, that can't find this package in your virtual environment. If you don't want to use tox, you can install the current version of the package with:
`pip install -e .` in your virtual environment.

**Comment by adamghill** [comment]
@dethi Ah, that all makes sense! Thank you for the explanation. `tox` worked fine once I tried that.

I'm now getting multiple errors trying to make calls to algolianet.com, though.
```
AlgoliaException: Unreachable hosts: {'None-1.algolianet.com': "HTTPSConnectionP
ool(host='None-1.algolianet.com', port=443): Max retries exceeded with url: /1/i
ndexes/django_Example_test_tmp/clear```

Maybe missing a environment variable?

**Comment by dethi** [comment]
Yes. You need to define:
- ALGOLIA_APPLICATION_ID
- ALGOLIA_API_KEY

Like this:
```bash
$ ALGOLIA_APPLICATION_ID=YourAppId ALGOLIA_API_KEY=YourSecretKey tox
```

**Comment by dethi** [comment]
@adamghill Good idea the documentation! :+1: 
I will merge your PR tomorrow.

**Pull request merged**
